[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
netsepio = "HtXkraCSZsMYEpjvyNhCX4JMpMAvykp63vuP8obMfzo2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/soumalya/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
