[package]
name = "erberus"
version = "1.0.0"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git' 
rev = 'main'
subdir = 'aptos-move/framework/aptos-token-objects'

[addresses]
admin = "0x6299daec2e0c0e0f8c0f824bd91290286af7d709375b4c9593858d49a2227a40"
VSEED = ""
wv1 = "" 
std = "0x1"
aptos_token_objects ="0x4"