[package]
name = "reviews"
version = "1.0.6"
upgrade_policy = "compatible"

[addresses]
admin = "_"
RSEED = "0xB09E24C"

[dependencies]
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects/", rev = "aptos-cli-v2.0.2" }